version: '2'
services:
  cassandra:
    image: cassandra:4.1.0
    container_name: rockthejvm-flink-cassandra
    ports:
      - "7000:7000"
      - "9042:9042"
    environment:
      - "CASSANDRA_CLUSTER_NAME=OUR_DOCKERIZED_CASSANDRA_SINGLE_NODE_CLUSTER"
      - "CASSANDRA_BROADCAST_ADDRESS=127.0.0.1"